language: ruby
rvm:
 - 2.3.0

services:
 - postgresql

before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
 - cp config/database.yml.travis config/database.yml
 - bundle exec rake db:migrate
 - bundle exec rake db:reset

# uncomment and edit the following line if your project needs to run something other than `rake`:
script: bundle exec rspec
